version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGPASSWORD=employeepw
      - PGPORT=5432
    depends_on: 
      - db
    volumes: 
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: postgres
    environment: 
      - POSTGRES_DB=employee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=employeepw
volumes:
  dbdata:
